config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'dashboard', to: 'pages#dashboard'
  get 'refresh_dashboard', to: 'pages#refresh_dashboard'
  get 'random_items', to: 'items#random'
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emotion.rb
class Emotion < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :emotions

  def self.count_emotions(month, emotion_title)
    Emotion.where(title: emotion_title).where(item_id: Item.by_month(month, year: 2017)).count
  end

  def self.count_king_emotions(month)
    Emotion.where(item_id: Item.by_month(month, year: 2017)).group(:title).count.values.max
  end

  def self.count_month(month)
    Emotion.where(item_id: Item.by_month(month, year: 2017)).count
  end

  def self.sizes(total, month)
    result = []
    %w(Joy Happy Satisfied Fun Depressed Exhausted Annoyed Nervous).each do |emotion_title|
      result << size(total, month, emotion_title, result.try(:last) || 0)
    end
    result << result.last + result[0] / 2

    result
  end

  def self.size(total, month, emotion_title, before_size)
    total * count_emotions(month, emotion_title) / count_month(month) + before_size
  end

  def self.ops(max, month)
    result = []
    %w(Joy Happy Satisfied Fun Depressed Exhausted Annoyed Nervous).each do |emotion_title|
      result << max * count_emotions(month, emotion_title) / count_king_emotions(month)
    end
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @item = Item.order('RAND()').first
  end

  def show
    @item = Item.find(params[:id])
  end

  def random
    @item = Item.order('RAND()').where.not(id: params[:current_item_ids]).first
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    params[:item][:emotions].reject { |e| e.blank? }.each do |title|
      @item.emotions.build(title: title)
    end
    if @item.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to :index
  end

  private

  def item_params
    params.require(:item).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @item = Item.order('RAND()').first
    @item2 = Item.order('RAND()').where.not(id: @item.id).first
  end

  def refresh_dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.haml
= form_for @item do |f|
  .form-group
    = f.label :emotions, 'I am feeling.....'
    = f.select :emotions, {'Joy': 'Joy', 'Happy': 'Happy', 'Satisfied': 'Satisfied', 'Fun': 'Fun', 'Depressed': 'Depressed', 'Exhausted': 'Exhausted', 'Annoyed': 'Annoyed', 'Nervous': 'Nervous'}, {}, class: 'form-control', id: 'js-emoji-select', multiple: 'multiple'
  .form-group{style:"margin-top:40px;"}
    = f.label :content, 'Because today....'
    = f.text_area :content, rows: 15, class: 'form-control'
  .form-group{style:"margin-top:40px;"}
    .pull-left
      %button.btn.btn-default.btn-lg{onclick: "javascript:history.back();'"}
        back
    .pull-right
      = f.submit 'save', class: 'btn btn-primary btn-lg'

app/views/items/_show.html.haml
- color_map = {'Joy': '#FA8DBE', 'Happy': '#FAAA94', 'Satisfied': '#FCEDB7', 'Fun': '#90E3D5', 'Depressed': '#79D7FC', 'Exhausted': '#C2B0E9', 'Annoyed': '#D362E8', 'Nervous': '#7B78EB'}
- color_map_light_ratio = '0.5'
- color_map_light = { 'Joy': "hsla(332.9, 91.2%, 86.7%, #{color_map_light_ratio})" , 'Happy': "hsla(12.9, 91.1%, 78%, #{color_map_light_ratio})" , 'Satisfied': "hsla(47, 92%, 85.3%, #{color_map_light_ratio})" , 'Fun': "hsla(169.9, 59.7%, 72.7%, #{color_map_light_ratio})" , 'Depressed': "hsla(196.9, 95.6%, 73.1%, #{color_map_light_ratio})" , 'Exhausted': "hsla(241.6, 74.2%, 69.6%, #{color_map_light_ratio})" , 'Annoyed': "hsla(258.9, 56.4%, 80.2%, #{color_map_light_ratio})" , 'Nervous': "rgba(207, 176, 233, #{color_map_light_ratio})" }

- if item.emotions.any?
  - if item.emotions.count > 1
    - background_option = item.emotions.map { |emotion| color_map.select { |k, _| k.to_s == emotion.title }.map { |_, v| v }.join(',') }.join(', ')
  - elsif item.emotions.count == 1
    - color = color_map[item.emotions.first.title.to_sym]
    - color_map_light = color_map_light[item.emotions.first.title.to_sym]
    - background_option = "#{color}, #{color_map_light}"
  - background_style = "background:linear-gradient(" + background_option + ")";
- else
  - background_style = "";

.show-area[item]{ style:"#{background_style}", 'data-item-id': item.id }
  %p.content
    = item.content.truncate(70)
  .meta
    = item.created_at.to_date
    %br
    - item.emotions.each do |emotion|
      %img{src: asset_url("#{emotion.title}_Emoji.png")}
  .control{style:"display:none;"}
    = link_to '삭제', item, method: :delete, data: { confirm: '정말 삭제하시겠습니까?'}

app/views/items/index.html.haml
- if @item.present?
  %p
    != simple_format @item.content
  %p
    = @item.emotion

  .control
    = link_to '다른 아이템 보기', items_path
.control
  = link_to '쓰기', new_item_path

app/views/items/new.html.haml
%section#create-section
  .container
    = render 'items/form'

app/views/items/random.js.erb
var $target = $(".card").hasClass('flipped') ? $(".card > .card-item:first-child") : $(".card > .card-item:last-child");
$target.html('<%= escape_javascript(render 'items/show', item: @item ) %>')
$(".card").toggleClass('flipped');

app/views/items/show.html.haml
= render 'items/show', item: @item

app/views/layouts/application.html.haml
!!!
%html{:lang => I18n.locale}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no", :name => "viewport"}
    = stylesheet_link_tag 'application', media: 'all'
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet"}

    = csrf_meta_tags

    %title
      항해일지
  %body{class: "app-#{params[:controller]} app-#{params[:controller]}-#{params[:action]}"}
    / - unless content_for?(:header)
    /   %section
    /     %nav.navbar.navbar-default.navbar-static-top
    /       .container{style:"margin: 20px;"}
    /         .text-center.header-title
    /           Sailing Diary

    = yield

    = javascript_include_tag 'application'
    %script{:src => "//d3js.org/d3.v3.min.js"}
    = yield :script if content_for?(:script)

app/views/pages/_background_style.html.erb
<%
size_640 = Item.sizes(340, month)
size_480 = Item.sizes(280, month)
size_800 = Item.sizes(400, month)
deg = rand(40)-20
ops = Item.ops(0.7, month)
-%>repeating-linear-gradient(<%= 190+deg %>deg,
hsla(332.9, 91.2%, 86.7%, <%= ops[0] %>) <%= size_640[0] %>px,
hsla(12.9, 91.1%, 78%, <%= ops[1] %>) <%= size_640[1] %>px,
hsla(47, 92%, 85.3%, <%= ops[2] %>) <%= size_640[2] %>px,
hsla(169.9, 59.7%, 72.7%, <%= ops[3] %>) <%= size_640[3] %>px,
hsla(196.9, 95.6%, 73.1%, <%= ops[4] %>) <%= size_640[4] %>px,
hsla(241.6, 74.2%, 69.6%, <%= ops[5] %>) <%= size_640[5] %>px,
hsla(258.9, 56.4%, 80.2%, <%= ops[6] %>) <%= size_640[6] %>px,
rgba(207, 176, 233, <%= ops[7] %>) <%= size_640[7] %>px,
hsla(332.9, 91.2%, 86.7%, <%= ops[0] %>) <%= size_640[8] %>px),
repeating-linear-gradient(<%= -(190+deg) %>deg,
hsla(332.9, 91.2%, 86.7%, <%= ops[0] %>) <%= size_480[0] %>px,
hsla(12.9, 91.1%, 78%, <%= ops[1] %>) <%= size_480[1] %>px,
hsla(47, 92%, 85.3%, <%= ops[2] %>) <%= size_480[2] %>px,
hsla(169.9, 59.7%, 72.7%, <%= ops[3] %>) <%= size_480[3] %>px,
hsla(196.9, 95.6%, 73.1%, <%= ops[4] %>) <%= size_480[4] %>px,
hsla(241.6, 74.2%, 69.6%, <%= ops[5] %>) <%= size_480[5] %>px,
hsla(258.9, 56.4%, 80.2%, <%= ops[6] %>) <%= size_480[6] %>px,
rgba(207, 176, 233, <%= ops[7] %>) <%= size_480[7] %>px,
hsla(332.9, 91.2%, 86.7%, <%= ops[0] %>) <%= size_480[8] %>px),
repeating-linear-gradient(23deg,
hsla(332.9, 91.2%, 86.7%, 1) <%= size_800[0] %>px,
hsla(12.9,91.1%,78%, 1) <%= size_800[1] %>px,
hsla(47,92%,85.3%, 1) <%= size_800[2] %>px,
hsla(169.9,59.7%,72.7%, 1) <%= size_800[3] %>px,
hsla(196.9,95.6%,73.1%, 1) <%= size_800[4] %>px,
hsla(241.6,74.2%,69.6%, 1) <%= size_800[5] %>px,
hsla(258.9,56.4%,80.2%, 1) <%= size_800[6] %>px,
rgba(207, 176, 233, 1) <%= size_800[7] %>px,
hsla(332.9, 91.2%, 86.7%, 1) <%= size_800[8] %>px)

app/views/pages/_dashboard_style.html.haml
:css
  .multi-repeating-linear[data-month='#{month}'] {
    height: 100%;
    width: 100%;
    background: #{render 'pages/background_style', local_assigns };
    background-blend-mode: multiply;
    background-size: 102% 102%;
  }

app/views/pages/dashboard.html.haml
= render 'pages/dashboard_style', month: 7
= render 'pages/dashboard_style', month: 8
= render 'pages/dashboard_style', month: 9
= render 'pages/dashboard_style', month: 10
%section#dashboard-section
  .graph.slideshow-container
    .title.pull-right
      %div{style:"margin:40px 0px;"}
        Sailing
        %br
        Diary
        %br
        %span{style:"display:block;margin-top:-10px;padding-left:10px;"}
          Parti
    .color-pallet
      %table
        %tr
          %td.color-box{style:"background-color: #fa8dbe"}
          %td
            Joy
        %tr
          %td.color-box{style:"background-color: #faaa94"}
          %td
            Happy
        %tr
          %td.color-box{style:"background-color: #fcedb7"}
          %td
            Satisfied
        %tr
          %td.color-box{style:"background-color: #90e3d5"}
          %td
            Fun
        %tr
          %td.color-box{style:"background-color: #79d7fc"}
          %td
            Depressed
        %tr
          %td.color-box{style:"background-color: #7b78eb"}
          %td
            Exhausted
        %tr
          %td.color-box{style:"background-color: #d362e8"}
          %td
            Annoyed
        %tr
          %td.color-box{style:"background-color: #cfb0e9"}
          %td
            Nervous

    #js-slideshow{ 'data-url': refresh_dashboard_path }
      .js-slide-item.multi-repeating-linear{ 'data-month': 7 }
        .period-box.text-center
          2017.07.01 ~ 2017.07.31
      .js-slide-item.multi-repeating-linear{ 'data-month': 8 }
        .period-box.text-center
          2017.08.01 ~ 2017.08.31
      .js-slide-item.multi-repeating-linear{ 'data-month': 9 }
        .period-box.text-center
          2017.09.01 ~ 2017.09.30
      .js-slide-item.multi-repeating-linear{ 'data-month': 10 }
        .period-box.text-center
          2017.10.01 ~ 2017.10.31
      .js-slide-item.multi-repeating-linear{ 'data-month': 11 }
        .period-box.text-center
          2017.11.01 ~ 2017.11.30
  .feed
    %h3
      How was your day?
    .show-item{ "data-url": random_items_path }
      .card
        .card-item
          = render 'items/show', item: @item
        .card-item

app/views/pages/home.html.haml
%section#welcome-section
  .container
    .title-box.text-left
      %h2
        How are you
        %br
        feeling today?
      = link_to 'Tell us !', new_item_path, class: 'btn btn-default'

app/views/pages/refresh_dashboard.js.erb
$('#js-slideshow > .js-slide-item:nth(1)').css('background', '<%= escape_javascript(render 'pages/background_style', month: params[:month]) %>');